logging:
  level:
    org.springframework.cloud.gateway: DEBUG
mybatis-plus:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8500
spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DATABASE}?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=UTC
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USER}
    password: ${RABBITMQ_PASSWORD}
    virtual-host: ${RABBITMQ_VHOST}
  cloud:
    loadbalancer:
      nacos:
        enabled: true
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: video_service
          uri: lb://video-service
          predicates:
            - Path=/api/video/**, /api/post/**
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/user/**
    nacos:
      discovery:
        server-addr: 1.94.63.237:8848
user:
  white-list: # 白名单
    - /login
    - /logout